package com.meden.lens.analysis.domain;

public enum FindingCode {
    EXCESSIVE_MODEL_CALLS,
    EXCESSIVE_TOOL_USAGE,
    TOKEN_BUDGET_EXCEEDED,
    INPUT_CONTEXT_TOO_LARGE,
    OUTPUT_TOO_VERBOSE,
    COST_DISPROPORTIONATE_TO_TASK,
    LATENCY_ABOVE_EXPECTED,
    RETRY_LOOP_DETECTED,
    UNNECESSARY_SUB_AGENTS,
    TOOLS_USED_FOR_NON_TOOL_TASK,
    PREMIUM_MODEL_FOR_SIMPLE_TASK,
    FAILED_RUN_WITH_HIGH_COST,
    INSUFFICIENT_EXECUTION,
    BALANCED_EXECUTION
}
