package com.meden.lens.analysis.domain;

public enum RecommendationCode {
    REDUCE_MODEL_CALLS,
    REDUCE_TOOL_CALLS,
    DISABLE_UNNECESSARY_TOOLS,
    SET_TOKEN_BUDGET,
    REDUCE_CONTEXT_SIZE,
    USE_SMALLER_MODEL,
    ADD_RETRY_LIMIT,
    DISABLE_SUB_AGENTS,
    CACHE_REPEATED_RESULTS,
    USE_DETERMINISTIC_CODE,
    SPLIT_TASK_INTO_STAGES,
    REVIEW_TASK_PROFILE
}
